name: Simple Local
on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    defaults:
      run:
        working-directory: Lab02
    steps:
      - uses: actions/checkout@v3
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm install --save moment
      - run: node app.js